# External Ansible roles required by this repository

- src: openmicroscopy.basedeps
  version: 1.0.0

#- src: openmicroscopy.ice
#  version: 2.0.0
- name: openmicroscopy.ice
  src: https://github.com/manics/ansible-role-ice/archive/ice-devel-optional.tar.gz
  version: ice-devel-optional

- src: openmicroscopy.java
  version: 2.0.0

- src: openmicroscopy.omego
  version: 0.1.0

- src: openmicroscopy.omero-common
  version: 0.1.0

- src: openmicroscopy.omero-python-deps
  version: 1.1.0

- name: openmicroscopy.omero-server
#  version: 2.0.0-m1
  src: https://github.com/manics/ansible-role-omero-server/archive/devel.tar.gz

- src: openmicroscopy.postgresql
  version: 2.0.0
